name: Build and Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: g++ init.cpp -fopenmp src/*.cpp -o program

    - name: Run
      run: ./program < input
